version: "3.7"

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:4
    ports:
      - 6379:6379
  worker:
    build: .
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./mysite:/code/server
    command: celery -A mysite worker -l info
  server:
    build: .
    depends_on:
      - worker
    ports:
      - 8000:8000
    volumes:
      - ./mysite:/code/server
